# Generated by Django 4.0.4 on 2022-07-17 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('D_Name', models.CharField(max_length=7, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reg_St_Sem',
            fields=[
                ('rs', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester', models.CharField(max_length=6, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Code', models.CharField(max_length=10)),
                ('C_Title', models.CharField(max_length=100)),
                ('C_Credit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('C_Department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CR_Home.department')),
            ],
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('C_Code', 'C_Department'), name='unique_course'),
        ),
    ]
