# Generated by Django 4.0.4 on 2022-08-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CR_Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_cbr',
            name='SCBR_Slip',
            field=models.FileField(upload_to=''),
        ),
    ]
