# Generated by Django 4.0.4 on 2022-07-26 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CR_Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='C_Semester',
            field=models.ForeignKey(default='NA', on_delete=django.db.models.deletion.PROTECT, to='CR_Home.semester'),
        ),
        migrations.AddField(
            model_name='course',
            name='C_Year',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='CR_Home.year'),
        ),
        migrations.CreateModel(
            name='Stu_Course_Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCR_Roll', models.IntegerField()),
                ('SCR_C_Code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CR_Home.course')),
                ('SCR_RS_Sem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CR_Home.reg_st_sem')),
            ],
        ),
    ]
