# Generated by Django 4.0.4 on 2022-08-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CR_Home', '0002_alter_stu_cbr_scbr_slip'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='C_Optional',
            field=models.BooleanField(default=False),
        ),
    ]
