# Generated by Django 4.0.4 on 2022-09-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CR_Home', '0003_course_c_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_cbr',
            name='SCBR_T_AC',
            field=models.BooleanField(default=False),
        ),
    ]
