# Generated by Django 4.0.4 on 2022-08-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_student_s_c_end_d_student_s_c_start_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='S_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='T_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
