# Generated by Django 4.0.4 on 2022-08-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_student_s_is_active_teacher_t_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='T_Designation',
            field=models.CharField(default='Not Added', max_length=30),
        ),
    ]
